title: Jiayuan Wang # your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/jiayuan-wang-9006aa177/">resume</a> 
  <br> 
  Email: wang(dot)6195(at)osu.edu
  <br><br>
  <a href="https://www.linkedin.com/in/jiayuan-wang-9006aa177/">LinkedIn</a> 
  <br>
  <a href="https://www.linkedin.com/in/jiayuan-wang-9006aa177/">GitHub</a> 
  <br>
  <a href="https://scholar.google.com/citations?user=kf3QgE4AAAAJ&hl=en">Google Scholar</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
